version: "3"

services:
  client:
    container_name: clang-client
    build:
      context: clang-client/
    restart: always
    ports:
      - "2222:22"
    environment:
      - PUBLIC_KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILuZdFNd5f8bgnvulkksxlT5209PNTHur+ukBsDs5quN maxalex301@gmail.com

  server:
    container_name: clang-server
    build:
      context: clang-server/
    environment:
      - NETWORK=10.0.0.1/16
      - JOBS=3
    ports:
      - "3632:3632"
    user: distccd