version: "3"

services:
  build-client:
    container_name: build-client
    build:
      context: build-client/
    restart: always
    ports:
      - "22222:22"
    environment:
      - PUBLIC_KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILuZdFNd5f8bgnvulkksxlT5209PNTHur+ukBsDs5quN maxalex301@gmail.com
      - CC=/usr/local/bin/clang
      - CXX=/usr/local/bin/clang++
      - FC=/usr/local/bin/gfortran

  build-server:
    container_name: build-server
    build:
      context: build-server/
    environment:
      - NETWORK=10.0.0.1/16
      - JOBS=3
    ports:
      - "3632:3632"
    user: distccd
