version: "3"

services:
  build-server:
    container_name: build-server
    image: maxalex/build-server
    environment:
      - ALLOW="-a 10.100.0.1/24 -a 192.168.101.0/24"
      - JOBS=3
    ports:
      - "3692:3692"
    user: distccd
