version: "3"

services:
  build-server:
    container_name: build-server
    image: maxalex/build-server
    environment:
      - ALLOW="--allow=10.0.0.1/16"
      - JOBS=3
    ports:
      - "3632:3632"
    user: distccd
